tasks:
  - name: Start Elasticsearch
    init: |
      sudo apt update
      sudo apt install -y docker.io
      docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 docker.elastic.co/elasticsearch/elasticsearch:latest
    command: sleep infinity
    ports:
      - port: 9200
        onOpen: open-preview
